// Code generated by swaggo/swag. DO NOT EDIT.

package swag

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/Converter/GetFisrtImageByGavingKey": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "根据文件key或者文件url获取文件并转成相应的目标图片，只转第一个图层或者第一页，目前支持psd-\u003ejpeg;ai-\u003ejpeg;pdf-\u003ejpeg",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "GetFisrtImageByGavingKey"
                ],
                "summary": "GetFisrtImageByGavingKey",
                "parameters": [
                    {
                        "description": "request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/converter.ConvertByGavingKeyRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/converter.ConvertByGavingKeyResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.CommonErrorResponse"
                        }
                    }
                }
            }
        },
        "/Converter/GetPdfByGavingKey": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "根据文件key或者文件url获取文件并转成相应的目标pdf，只转第一个图层或者第一页，目前支持psd-\u003epdf;ai-\u003epdf;pdf-\u003epdf",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "GetPdfByGavingKey"
                ],
                "summary": "GetPdfByGavingKey",
                "parameters": [
                    {
                        "description": "request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/converter.ConvertByGavingKeyRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/converter.ConvertByGavingKeyResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.CommonErrorResponse"
                        }
                    }
                }
            }
        },
        "/GetImgInfo": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "批量获取图片宽高，只支持png,jpg,gif类型图片",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "GetImgInfo"
                ],
                "summary": "GetImgInfo",
                "parameters": [
                    {
                        "description": "request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/imginfo.GetImgInfoRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/imginfo.GetImgInfoResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.CommonErrorResponse"
                        }
                    }
                }
            }
        },
        "/Tar/Pack": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "根据文件key或者文件url归档，或者归档压缩生成文件,目前只支持归档成zip或者zip.gz文件",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PackByGavingKey"
                ],
                "summary": "PackByGavingKey",
                "parameters": [
                    {
                        "description": "request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/tar.PackRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.CommandResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.CommonErrorResponse"
                        }
                    }
                }
            }
        },
        "/Zip/Pack": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "根据文件key或者文件url归档，或者归档压缩生成文件,目前只支持归档成zip或者zip.gz文件",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "PackByGavingKey"
                ],
                "summary": "PackByGavingKey",
                "parameters": [
                    {
                        "description": "request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/tar.PackRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.CommandResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.CommonErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "converter.ConvertByGavingKeyRequest": {
            "type": "object",
            "required": [
                "items"
            ],
            "properties": {
                "items": {
                    "type": "array",
                    "maxItems": 10,
                    "minItems": 1,
                    "items": {
                        "$ref": "#/definitions/converter.ConvertByGavingKeyRequestItem"
                    }
                }
            }
        },
        "converter.ConvertByGavingKeyRequestItem": {
            "type": "object",
            "required": [
                "sourceKey",
                "targetKey"
            ],
            "properties": {
                "sourceKey": {
                    "description": "@description 如果这个值为合法url就会根据url地址获取源文件，如果不是则默认为文件key，通过minio获取文件",
                    "type": "string"
                },
                "targetFileDpi": {
                    "type": "integer"
                },
                "targetKey": {
                    "type": "string"
                }
            }
        },
        "converter.ConvertByGavingKeyResponse": {
            "type": "object",
            "required": [
                "isAllSucceed",
                "items"
            ],
            "properties": {
                "isAllSucceed": {
                    "type": "boolean"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/converter.ConvertByGavingKeyResponseItem"
                    }
                }
            }
        },
        "converter.ConvertByGavingKeyResponseItem": {
            "type": "object",
            "required": [
                "isSucceed",
                "sourceKey"
            ],
            "properties": {
                "isSucceed": {
                    "type": "boolean"
                },
                "message": {
                    "type": "string"
                },
                "sourceKey": {
                    "type": "string"
                },
                "targetFileSize": {
                    "type": "integer"
                }
            }
        },
        "imginfo.GetImgInfoItemResponse": {
            "type": "object",
            "required": [
                "fileKey"
            ],
            "properties": {
                "fileKey": {
                    "type": "string"
                },
                "isSucceed": {
                    "type": "boolean"
                },
                "message": {
                    "type": "string"
                },
                "width": {
                    "type": "integer"
                }
            }
        },
        "imginfo.GetImgInfoRequest": {
            "type": "object",
            "required": [
                "items"
            ],
            "properties": {
                "items": {
                    "type": "array",
                    "maxItems": 20,
                    "minItems": 1,
                    "items": {
                        "$ref": "#/definitions/imginfo.GetImgInfoRequestItem"
                    }
                }
            }
        },
        "imginfo.GetImgInfoRequestItem": {
            "type": "object",
            "properties": {
                "fileKey": {
                    "description": "@description minio文件key",
                    "type": "string"
                }
            }
        },
        "imginfo.GetImgInfoResponse": {
            "type": "object",
            "required": [
                "items"
            ],
            "properties": {
                "isAllSucceed": {
                    "type": "boolean"
                },
                "items": {
                    "type": "array",
                    "maxItems": 20,
                    "minItems": 1,
                    "items": {
                        "$ref": "#/definitions/imginfo.GetImgInfoItemResponse"
                    }
                }
            }
        },
        "models.AclError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "details": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "requestStack": {
                    "type": "string"
                },
                "validationErrors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.ValidationError"
                    }
                }
            }
        },
        "models.CommandResponse": {
            "type": "object",
            "properties": {
                "isSuccessd": {
                    "type": "boolean"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "models.CommonErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/models.AclError"
                }
            }
        },
        "models.ValidationError": {
            "type": "object",
            "properties": {
                "members": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "tar.PackRequest": {
            "type": "object",
            "properties": {
                "fileKey": {
                    "type": "string"
                },
                "isGziped": {
                    "type": "boolean"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/tar.PackRequestItem"
                    }
                }
            }
        },
        "tar.PackRequestItem": {
            "type": "object",
            "properties": {
                "fileKey": {
                    "description": "@description 如果此参数是一个合法的url则会根据url获取文件，否则视为minio文件key",
                    "type": "string"
                },
                "fileName": {
                    "description": "文件夹层级用\"/\"表示",
                    "type": "string"
                },
                "lastModifyTime": {
                    "description": "ISO 8601 时间",
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
