definitions:
  converter.ConvertByGavingKeyRequest:
    properties:
      items:
        items:
          $ref: '#/definitions/converter.ConvertByGavingKeyRequestItem'
        maxItems: 10
        minItems: 1
        type: array
    required:
    - items
    type: object
  converter.ConvertByGavingKeyRequestItem:
    properties:
      sourceKey:
        type: string
      targetKey:
        type: string
    required:
    - sourceKey
    - targetKey
    type: object
  converter.ConvertByGavingKeyResponse:
    properties:
      isAllSucceed:
        type: boolean
      items:
        items:
          $ref: '#/definitions/converter.ConvertByGavingKeyResponseItem'
        type: array
    required:
    - isAllSucceed
    - items
    type: object
  converter.ConvertByGavingKeyResponseItem:
    properties:
      isSucceed:
        type: boolean
      message:
        type: string
      sourceKey:
        type: string
    required:
    - isSucceed
    - sourceKey
    type: object
  models.AclError:
    properties:
      code:
        type: string
      details:
        type: string
      message:
        type: string
      requestStack:
        type: string
      validationErrors:
        items:
          $ref: '#/definitions/models.ValidationError'
        type: array
    type: object
  models.CommandResponse:
    properties:
      isSuccessd:
        type: boolean
      message:
        type: string
    type: object
  models.CommonErrorResponse:
    properties:
      error:
        $ref: '#/definitions/models.AclError'
    type: object
  models.ValidationError:
    properties:
      members:
        items:
          type: string
        type: array
      message:
        type: string
    type: object
  tar.PackRequest:
    properties:
      fileKey:
        type: string
      isGziped:
        type: boolean
      items:
        items:
          $ref: '#/definitions/tar.PackRequestItem'
        type: array
    type: object
  tar.PackRequestItem:
    properties:
      fileKey:
        type: string
      fileName:
        description: 文件夹层级用"/"表示
        type: string
      lastModifyTime:
        description: ISO 8601 时间
        type: string
    type: object
info:
  contact: {}
paths:
  /Converter/GetFisrtImageByGavingKey:
    post:
      consumes:
      - application/json
      description: GetFisrtImageByGavingKey
      parameters:
      - description: request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/converter.ConvertByGavingKeyRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/converter.ConvertByGavingKeyResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.CommonErrorResponse'
      security:
      - BearerAuth: []
      summary: GetFisrtImageByGavingKey
      tags:
      - GetFisrtImageByGavingKey
  /Converter/GetPdfByGavingKey:
    post:
      consumes:
      - application/json
      description: GetPdfByGavingKey
      parameters:
      - description: request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/converter.ConvertByGavingKeyRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/converter.ConvertByGavingKeyResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.CommonErrorResponse'
      summary: GetPdfByGavingKey
      tags:
      - GetPdfByGavingKey
  /Tar/Pack:
    post:
      consumes:
      - application/json
      description: PackByGavingKey
      parameters:
      - description: request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/tar.PackRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.CommandResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.CommonErrorResponse'
      security:
      - BearerAuth: []
      summary: PackByGavingKey
      tags:
      - PackByGavingKey
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
